project_id = "cfbrabjbkmnpqmdhzhbc"

[functions.ai-chat]
verify_jwt = false

[functions.redeem-coupon]
verify_jwt = false

[functions.gemini-ai]
verify_jwt = false

[functions.generate-study-plan]
verify_jwt = false
